### ISSUE TITLE
Save Permissions in Database

### ISSUE THREAD

**Issue by bypit** [micc83/rooles#3]
Hi, could you add database support for storing permissions in a future version?

**Comment by micc83** [comment]
As stated in the documentation rooles is meant to be a "very simple" roles and permission manager. Anyone can build his custom RBAC system around it. In order to keep it simple I've decided to leave database integration at developer discretion. If you need something more complex, with out of the box database support, I can suggest you to pick one of the many ACL system out there such as romanbican/roles, kodeine/laravel-acl or Sentinel.
